# Generated by Django 5.1.4 on 2024-12-16 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotions",
            fields=[
                ("promo_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "hotel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Tables.hotel"
                    ),
                ),
            ],
        ),
    ]
