# Generated by Django 5.1.4 on 2024-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="room_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
