# Generated by Django 5.1.4 on 2024-12-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_hotelbooking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="type",
            new_name="room_type",
        ),
    ]
